Employee Management System/Controllers/PerformanceReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Employee_Management_System.Data;
using Employee_Management_System.Models;
using Microsoft.AspNetCore.Authorization;

namespace Employee_Management_System.Controllers
{
   
    public class PerformanceReviewsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PerformanceReviewsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PerformanceReviews
        public async Task<IActionResult> Index(int? term)
        {
            IQueryable<PerformanceReview> performanceReviews = _context.PerformanceReviews.Include(pr => pr.Employee);

            if (term.HasValue)
            {
                performanceReviews = performanceReviews.Where(pr => pr.EmployeeId == term.Value);
            }

            return View(await performanceReviews.ToListAsync());
        }

        // GET: PerformanceReviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performanceReview = await _context.PerformanceReviews
                .Include(p => p.Employee)
                .Include(p => p.Reviewer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (performanceReview == null)
            {
                return NotFound();
            }

            return View(performanceReview);
        }

        // GET: PerformanceReviews/Create
        public IActionResult Create()

        {

            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Id");
            ViewData["ReviewerId"] = new SelectList(_context.Employees, "Id", "Id");
            return View();
        }

        // POST: PerformanceReviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        
        public async Task<IActionResult> Create([Bind("Id,EmployeeId,ReviewerId,ReviewDate,Comments,Rating")] PerformanceReview performanceReview)
        {

            if (performanceReview.EmployeeId == performanceReview.ReviewerId)
            {
                ModelState.AddModelError("", "Reviewer Id cannot be the same as Employee Id");
            }

            if (ModelState.IsValid)
            {
                _context.Add(performanceReview);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Id", performanceReview.EmployeeId);
            ViewData["ReviewerId"] = new SelectList(_context.Employees, "Id", "Id", performanceReview.ReviewerId);
            return View(performanceReview);

            
        }

        // GET: PerformanceReviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performanceReview = await _context.PerformanceReviews.FindAsync(id);
            if (performanceReview == null)
            {
                return NotFound();
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Id", performanceReview.EmployeeId);
            ViewData["ReviewerId"] = new SelectList(_context.Employees, "Id", "Id", performanceReview.ReviewerId);
            return View(performanceReview);
        }

        // POST: PerformanceReviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EmployeeId,ReviewerId,ReviewDate,Comments,Rating")] PerformanceReview performanceReview)
        {
            if (id != performanceReview.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(performanceReview);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PerformanceReviewExists(performanceReview.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Id", performanceReview.EmployeeId);
            ViewData["ReviewerId"] = new SelectList(_context.Employees, "Id", "Id", performanceReview.ReviewerId);
            return View(performanceReview);
        }

        // GET: PerformanceReviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performanceReview = await _context.PerformanceReviews
                .Include(p => p.Employee)
                .Include(p => p.Reviewer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (performanceReview == null)
            {
                return NotFound();
            }

            return View(performanceReview);
        }

        // POST: PerformanceReviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var performanceReview = await _context.PerformanceReviews.FindAsync(id);
            if (performanceReview != null)
            {
                _context.PerformanceReviews.Remove(performanceReview);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PerformanceReviewExists(int id)
        {
            return _context.PerformanceReviews.Any(e => e.Id == id);
        }

      /*  [HttpGet]

        public JsonResult LiveSearch(string term)
        {
            if (string.IsNullOrWhiteSpace(term))
            {
                return Json(new List<object>());
            }

            var query = _context.PerformanceReviews.Include(pr => pr.Employee).AsQueryable();

            if (int.TryParse(term, out int employeeId))
            {

            }
        } */
    }
}

Employee Management System/Views/PerformanceReviews/Create.cshtml
@model Employee_Management_System.Models.PerformanceReview

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PerformanceReview</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" class ="form-control" asp-items="ViewBag.EmployeeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ReviewerId" class="control-label"></label>
                <select asp-for="ReviewerId" class ="form-control" asp-items="ViewBag.ReviewerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ReviewDate" class="control-label"></label>
                <input asp-for="ReviewDate" class="form-control" />
                <span asp-validation-for="ReviewDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <input asp-for="Comments" class="form-control" />
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Employee Management System/Views/PerformanceReviews/Delete.cshtml
@model Employee_Management_System.Models.PerformanceReview

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PerformanceReview</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReviewDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReviewDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comments)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Reviewer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Reviewer.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Employee Management System/Views/PerformanceReviews/Details.cshtml
@model Employee_Management_System.Models.PerformanceReview

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PerformanceReview</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReviewDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReviewDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comments)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Reviewer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Reviewer.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Employee Management System/Views/PerformanceReviews/Edit.cshtml
@model Employee_Management_System.Models.PerformanceReview

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PerformanceReview</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" class="form-control" asp-items="ViewBag.EmployeeId"></select>
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReviewerId" class="control-label"></label>
                <select asp-for="ReviewerId" class="form-control" asp-items="ViewBag.ReviewerId"></select>
                <span asp-validation-for="ReviewerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReviewDate" class="control-label"></label>
                <input asp-for="ReviewDate" class="form-control" />
                <span asp-validation-for="ReviewDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <input asp-for="Comments" class="form-control" />
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Employee Management System/Views/PerformanceReviews/Index.cshtml
@model IEnumerable<Employee_Management_System.Models.PerformanceReview>

@{
    ViewData["Title"] = "Index";
}

<h1>Performance Reviews</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr class="table-primary">
            <th>
                @Html.DisplayNameFor(model => model.ReviewDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comments)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Reviewer)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr class="table-light">
            <td>
                @Html.DisplayFor(modelItem => item.ReviewDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comments)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reviewer.Id)
            </td>
            <td>
                    <a class="badge bg-primary" asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                    <a class="badge bg-primary" asp-action="Details" asp-route-id="@item.Id">Details</a> 
                    <a class="badge bg-primary" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
          <form asp-controller="PerformanceReviews" asp-action="Index" method="get">

             <p>
                 <input type="text" name="term" id="LiveSearch" placeholder="Enter employees ID.."/>
                <input class="submit-button"  type="submit" value="search" />

             </p>

          </form>
      
    </tbody>
</table>